# Generated by Django 4.2.7 on 2023-12-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='achievement',
            field=models.ManyToManyField(blank=True, null=True, to='classes.achievement'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.role'),
        ),
    ]
