# Generated by Django 4.2.7 on 2023-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_achievement_description_alter_group_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdays',
            name='shortname',
            field=models.CharField(blank=True, default='None', max_length=150, null=True),
        ),
    ]
