# Generated by Django 4.2.7 on 2024-01-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_weekdays_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, upload_to='achivments/'),
        ),
    ]
