# Generated by Django 4.2.7 on 2024-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logevent',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
